{
 "title": "Github Enterprise",
 "tags": [
  "github",
  "prod"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "SYSTEM STATS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU - All",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(aliasSub(*.*.cpu.percent-idle, 'percent-', ' '))"
    },
    {
     "target": "aliasByMetric(aliasSub(exclude(*.*.cpu.*, 'percent-idle'), 'percent-', ' '))"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "aliasByMetric(*.*.load.load.*)" }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(aliasSub(*.*.processes.*, 'ps_state-', ' '))"
    }
   ]
  },
  { "title": "MEMORY STATS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Memory - Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(aliasSub(*.*.memory.memory-free, 'memory-', ' '))"
    },
    {
     "target": "aliasByMetric(aliasSub(exclude(exclude(exclude(*.*.memory.*, 'memory-free'), 'memory-slab_recl'), 'memory-slab_unrecl'), 'memory-', ' '))"
    }
   ]
  },
  {
   "title": "Memory - I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(*.*.vmem.vmpage_io-memory.*)"
    }
   ]
  },
  {
   "title": "Memory - Used %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(scale(divideSeries(#B, #A), 100), 'Memory Used %')",
     "targetFull": "alias(scale(divideSeries(aliasByMetric(aliasSub(*.*.memory.memory-used, 'memory-', ' ')), sumSeries(aliasByMetric(aliasSub(*.*.memory.memory-used, 'memory-', ' ')), alias(aliasByMetric(sumSeries(exclude(*.*.memory.*, 'memory-used'), *)), 'Total Free'))), 100), 'Memory Used %')"
    }
   ]
  },
  { "title": "DISK USAGE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Disk - Root usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(aliasSub(*.*.df-root.*, 'df_complex-', ' '))"
    }
   ]
  },
  {
   "title": "Disk - Data usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(aliasSub(*.*.df-data-user.*, 'df_complex-', ' '))"
    }
   ]
  },
  {
   "title": "Disk - Root Percent Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(scale(divideSeries(#B, #C), 100), 'Root Percent Used')",
     "targetFull": "alias(scale(divideSeries(aliasSub(alias(aliasByMetric(*.*.df-root.df_complex-used), 'Total Used'), 'df_complex-', ' '), alias(sumSeries(exclude(*.*.df-root.*, 'df-complex_reserved'), *), 'Total Disk')), 100), 'Root Percent Used')"
    }
   ]
  },
  {
   "title": "Disk - Data Percent usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(scale(divideSeries(#B, #C), 100), 'Data Disk Percent Used')",
     "targetFull": "alias(scale(divideSeries(aliasSub(alias(aliasByMetric(*.*.df-data-user.df_complex-used), 'Total Used'), 'df_complex-', ' '), alias(sumSeries(exclude(*.*.df-data-user.*, 'df-complex_reserved'), *), 'Total Disk')), 100), 'Data Disk Percent Used')"
    }
   ]
  },
  { "title": "DISK STATS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Disk - vda",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(*.*.disk-vda.disk_ops.*)"
    }
   ]
  },
  {
   "title": "DISK - vdb",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(*.*.disk-vdb.disk_ops.*)"
    }
   ]
  },
  {
   "title": "DISK - vda2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(*.*.disk-vda2.disk_ops.*)"
    }
   ]
  },
  {
   "title": "Disk - vda - IO Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(*.*.disk-vda.disk_time.*)"
    }
   ]
  },
  {
   "title": "Disk - vdb - IO Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(*.*.disk-vdb.disk_time.*)"
    }
   ]
  },
  {
   "title": "Disk - vda2 - IO Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 39 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(*.*.disk-vda2.disk_time.*)"
    }
   ]
  },
  { "title": "APPLICATION", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "GitHub Exception Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByMetric(*.*.statsd.gauge-github_exception_github_count), 'gauge-github_exception_github_count', 'exception_count')"
    }
   ]
  },
  {
   "title": "Elasticsearch Heap Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 47 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(aliasSub(*.*.elasticsearch-github-enterprise.percent-jvm_mem_heap-used-percent, 'percent-jvm_mem_heap-used-percent', 'JVM Used %'))"
    }
   ]
  },
  {
   "title": "HAProxy Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasSub(*.*.haproxy-frontend-*.derive-error_request, 'haproxy-frontend-', ' '), 2)"
    }
   ]
  },
  { "title": "BACKGROUND JOBS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Resque Background Jobs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(exclude(aliasSub(*.*.resque.*, 'gauge-*', ' '), 'maint_git-server*'))"
    },
    {
     "target": "aliasByMetric(aliasSub(*.*.resque.gauge-maint_git-server-a2a657c6-709d-11e8-8ab7-b718aa259656, 'gauge-*', ' '))"
    }
   ]
  },
  {
   "title": "Hookshot Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasByMetric(*.*.listener-hookshot.*), 'gauge-active', 'Active'), 'gauge-queued', 'Queued')"
    }
   ]
  },
  { "title": "NETWORK STATS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Network Connections - By Port",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(*.*.tcpconns-443-local.tcp_connections-ESTABLISHED, '443')"
    },
    {
     "target": "alias(*.*.tcpconns-80-local.tcp_connections-ESTABLISHED, '80')"
    },
    {
     "target": "alias(*.*.tcpconns-122-local.tcp_connections-ESTABLISHED, '122')"
    },
    {
     "target": "alias(*.*.tcpconns-22-local.tcp_connections-ESTABLISHED, '22')"
    },
    {
     "target": "alias(*.*.tcpconns-25-local.tcp_connections-ESTABLISHED, '25')"
    },
    {
     "target": "alias(*.*.tcpconns-9418-local.tcp_connections-ESTABLISHED, '9418')"
    }
   ]
  },
  {
   "title": "Network - Number of sockets per state",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(*.*.tcpconns-all.tcp_connections-TIME_WAIT, 'TimeWait')"
    },
    {
     "target": "alias(*.*.tcpconns-all.tcp_connections-CLOSE_WAIT, 'CloseWait')"
    },
    {
     "target": "alias(*.*.tcpconns-all.tcp_connections-ESTABLISHED, 'Established')"
    },
    {
     "target": "alias(*.*.tcpconns-all.tcp_connections-LISTEN, 'Listen')"
    },
    {
     "target": "alias(*.*.tcpconns-all.tcp_connections-FIN_WAIT1, 'FinWait')"
    }
   ]
  },
  {
   "title": "Protocol - UDP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(aliasSub(*.*.protocols-Udp.*, 'protocol_counter-', ' '))"
    }
   ]
  },
  {
   "title": "Protocol - TCP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(aliasSub(*.*.protocols-Tcp.protocol_counter-ActiveOpens, 'protocol_counter-', ' '))"
    },
    {
     "target": "aliasByMetric(aliasSub(*.*.protocols-Tcp.protocol_counter-PassiveOpens, 'protocol_counter-', ' '))"
    },
    {
     "target": "aliasByMetric(aliasSub(*.*.protocols-Tcp.protocol_counter-CurrEstab, 'protocol_counter-', ' '))"
    },
    {
     "target": "aliasByMetric(aliasSub(*.*.protocols-Tcp.protocol_counter-EstabResets, 'protocol_counter-', ' '))"
    },
    {
     "target": "aliasByMetric(aliasSub(*.*.protocols-Tcp.protocol_counter-MaxConn, 'protocol_counter-', ' '))"
    }
   ]
  },
  {
   "title": "Protocol - TCP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(aliasSub(*.*.protocols-Tcp.protocol_counter-AttemptFails, 'protocol_counter-', ' '))"
    },
    {
     "target": "aliasByMetric(aliasSub(*.*.protocols-Tcp.protocol_counter-InCsumErrors, 'protocol_counter-', ' '))"
    },
    {
     "target": "aliasByMetric(aliasSub(*.*.protocols-Tcp.protocol_counter-InErrs, 'protocol_counter-', ' '))"
    },
    {
     "target": "aliasByMetric(aliasSub(*.*.protocols-Tcp.protocol_counter-InSegs, 'protocol_counter-', ' '))"
    },
    {
     "target": "aliasByMetric(aliasSub(*.*.protocols-Tcp.protocol_counter-OutRsts, 'protocol_counter-', ' '))"
    },
    {
     "target": "aliasByMetric(aliasSub(*.*.protocols-Tcp.protocol_counter-OutSegs, 'protocol_counter-', ' '))"
    }
   ]
  },
  { "title": "MYSQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "MySQL Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(*.*.mysql-github.mysql_commands-insert, 'insert')"
    },
    {
     "target": "alias(*.*.mysql-github.mysql_commands-select, 'select')"
    },
    {
     "target": "alias(*.*.mysql-github.mysql_commands-update, 'update')"
    },
    {
     "target": "alias(*.*.mysql-github.mysql_commands-delete, 'delete')"
    },
    {
     "target": "alias(*.*.mysql-github.mysql_commands-begin, 'begin')"
    },
    {
     "target": "alias(*.*.mysql-github.mysql_commands-commit, 'commit')"
    },
    {
     "target": "alias(*.*.mysql-github.mysql_commands-update_multi, 'update-multi')"
    }
   ]
  },
  { "title": "REPLICA PING", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Replica-ping-alert",
   "type": "graph",
   "description": "Relica > 1.0",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "*.*.ping.ping-github-replica" }
   ]
  }
 ]
}